### ISSUE TITLE
Issue with audio inference

### ISSUE THREAD

**Issue by karlbernard2** [rlleshi/phar#1]
I'm trying to test your model, but I ran into an issue with the audio inference, maybe you would have some ideas what could be wrong?

`docker run --gpus all rlleshi/phar python src/demo/multimodial_demo.py /mnt/videos/tr_87505_hd.mp4 /mnt/videos/demo.mp4
Resizing video for faster inference...
Moviepy - Building video temp/tr_87505_hd.mp4.                        
MoviePy - Writing audio in tr_87505_hdTEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video temp/tr_87505_hd.mp4

Moviepy - Done !
Moviepy - video ready temp/tr_87505_hd.mp4
load checkpoint from local path: checkpoints/har/timeSformer.pth
Performing RGB inference...
100%|██████████| 12/12 [00:17<00:00,  1.44s/it]load checkpoint from local path: checkpoints/har/audio.pth
Performing audio inference...

  8%|▊         | 1/12 [00:14<02:43, 14.88s/it]
Traceback (most recent call last):
  File "src/demo/multimodial_demo.py", line 601, in <module>
    main()
  File "src/demo/multimodial_demo.py", line 562, in main
    audio_inference(clip, args.coefficients)
  File "src/demo/multimodial_demo.py", line 385, in audio_inference
    results = inference_recognizer(AUDIO_MODEL, out_feature)
  File "/workspace/phar/mmaction2/mmaction/apis/inference.py", line 99, in inference_recognizer
    raise RuntimeError('The type of argument video is not supported: '
RuntimeError: The type of argument video is not supported: <class 'str'>`

**Comment by rlleshi** [comment]
Hi karlbernard,
could you try to put a `time.sleep(1)` just above `results = inference_recognizer(AUDIO_MODEL, out_feature)`, [here](https://github.com/rlleshi/phar/blob/2869ffdb7b9aacc74c4eb5f8671110c2fa98dacb/src/demo/multimodial_demo.py#L384)?

`subprocess.run` is supposed to be blocking through.

**Comment by gauharbains** [comment]
I'm running into a similar issue. Does this ^ fix it ?

**Comment by gauharbains** [comment]
@rlleshi I tried this, but it didn't solve it.

**Comment by rlleshi** [comment]
@gauharbains could you please try to apply this fix in this PR [here](https://github.com/open-mmlab/mmaction2/pull/1652/files).

So just replace the glob search in `mmaction2/tools/data/build_audio_features.py` file with this line: 

`files = glob.glob(args.audio_home_path + '/*' * args.level + args.ext)`

**Comment by gauharbains** [comment]
@rlleshi That worked for me, thanks!

**Comment by rlleshi** [comment]
Fixed at 4a14ea4e9885bc3801f3219382ba59295258d106
