### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by smegmarip** [rlleshi/phar#12]
I feel that image processing would be a relatively easy proposition with your library, but before I attempt my own solution, I wanted to ask if you have (or can prepare) a demo that does single images. 
Thanks.

**Comment by rlleshi** [comment]
yeah, I think the demo script can be tuned accordingly. But it would require some work. Also, running all of these models on still images could be an overkill tbh.

However, I'm no longer actively working on this open-source version. Currently rather focusing on a commercial one.

**Comment by smegmarip** [comment]
Thanks for responding.  I figured that it would take some work.
