### ISSUE TITLE
Datasets used to train model

### ISSUE THREAD

**Issue by MartinDawson** [rlleshi/phar#18]
Hey,

Is their any chance we can get the dataset videos you used to train the model?

Thanks

**Comment by orangekittysoftware** [comment]
I really support this idea. Open access to the dataset would be very helpful. 

I also am wondering, what are the tools used for labelling? What is the process? There is some mention of labeling being labor-intensive, and I myself would like to try labeling.  

Willing assist in additional data prep, here.
