### ISSUE TITLE
can't seem to get it to run

### ISSUE THREAD

**Issue by cwilliamjay** [rlleshi/phar#3]
At first, I got Module Demo not found. I removed the period at demo.demo_skeleton import frame extraction. The multimodial_demo.py is in the same directory as the demo_skeleton.py I thought that was a path problem. Afterward, I get this:

  An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ... 
I'm using Windows 10 been trying for a few days can you help a noob out.

**Comment by rlleshi** [comment]
I am not sure about the installation on Windows. Could you try on [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) perhaps?

**Comment by cwilliamjay** [comment]
Thanks will try WSL

**Comment by rlleshi** [comment]
Otherwise, I would recommend that you try out the [docker](https://github.com/rlleshi/phar/blob/master/docker/Dockerfile) image. That should work without any problems.
