### ISSUE TITLE
Issue with audio in inference-recognizer

### ISSUE THREAD

**Issue by Arialphe** [rlleshi/phar#4]
Hello, I tried to test the app, but i got the same problem as the issue here:
https://github.com/rlleshi/phar/issues/1

Stack Trace:
File "src/demo/multimodial_demo.py", line 601, in <module>
    main()
  File "src/demo/multimodial_demo.py", line 562, in main
    audio_inference(clip, args.coefficients)
  File "src/demo/multimodial_demo.py", line 385, in audio_inference
    results = inference_recognizer(AUDIO_MODEL, out_feature)
  File "/workspace/phar/mmaction2/mmaction/apis/inference.py", line 99, in inference_recognizer
    raise RuntimeError('The type of argument video is not supported: '
RuntimeError: The type of argument video is not supported: <class 'str'>

I checked that the code is up to date, and it's the case:
line 381..:   
subprocess.run(
        ['python', AUDIO_FEATURE_SCRIPT, TEMP, TEMP, '--ext', 'wav'],
        capture_output=True)
        
Any ideas on what I'm doing wrong ?

**Comment by rlleshi** [comment]
Can you try to replace the glob search in `mmaction2/tools/data/build_audio_features.py` file with this line:

`files = glob.glob(args.audio_home_path + '/*' * args.level + '.' + args.ext)`
