### ISSUE TITLE
Any interest in collab?

### ISSUE THREAD

**Issue by skier233** [rlleshi/phar#5]
I've been looking into this topic for a while as well as similar topics: comprehensive automated tagging, personalized automated rating, automated video scripting for interactive content. I'd be interested in chatting and seeing if we have any insights that might be useful to one another. My discord is Skier23#9916

**Comment by rlleshi** [comment]
Sure. Would you mind sharing your email instead?

**Comment by skier233** [comment]
> Sure. Would you mind sharing your email instead?

benchy222@gmail.com
